reservation-hub/reshub

- app/server/src/controllers/API/areaController.js
- app/server/src/controllers/API/indexController.js
- app/server/src/controllers/API/shopController.js
- app/server/src/repositories/shopRepository.js
Add basic api read functions for shop with area details
> basic api - read functions

- app/client/package-lock.json
- app/client/package.json
- app/client/src/components/auth/LoginForm.js
- app/client/src/pages/auth/Auth.js
- app/client/src/store/actions/authAction.js
- app/client/src/store/reducers/areaReducer.js
- app/client/src/store/reducers/authReducer.js
- app/client/src/store/reducers/rootReducer.js
- app/client/src/store/types/authTypes.js
- app/client/src/utils/api/axios.js
- app/client/yarn.lock
Reverts reservation-hub/reshub#34
> Revert "add google login"

- app/prisma/migrations/20210806054639_id_to_id/migration.sql
- app/prisma/schema.prisma
- app/src/controllers/authController.ts
- app/src/controllers/reservationController.ts
- app/src/controllers/schemas/auth.ts
- app/src/controllers/schemas/google.ts
- app/src/controllers/schemas/reservation.ts
- app/src/controllers/schemas/shop.ts
- app/src/controllers/schemas/stylist.ts
- app/src/controllers/schemas/user.ts
- app/src/controllers/shopController.ts
- app/src/entities/OAuthIds.ts
- app/src/entities/Stylist.ts
- app/src/entities/User.ts
- app/src/errorHandler.ts
- app/src/repositories/LocationRepository.ts
- app/src/repositories/ReservationRepository.ts
- app/src/repositories/RoleRepository.ts
- app/src/repositories/ShopRepository.ts
- app/src/repositories/StylistRepository.ts
- app/src/repositories/UserRepository.ts
- app/src/routes/index.ts
- app/src/routes/passport.ts
- app/src/routes/utils.ts
- app/src/services/AuthService.ts
- app/src/services/Errors/ServiceError.ts
- app/src/services/ReservationService.ts
- app/src/services/ShopService.ts
- app/src/services/StylistService.ts
- app/src/services/UserService.ts
> fix error handling and google auth

- app/src/controllers/locationController.ts
- app/src/controllers/reservationController.ts
- app/src/controllers/roleController.ts
- app/src/controllers/shopController.ts
- app/src/controllers/stylistController.ts
- app/src/controllers/userController.ts
> fix returned values

- app/prisma/migrations/20210809143218_add_shop_schedule_json/migration.sql
- app/prisma/schema.prisma
- app/src/controllers/schemas/shop.ts
- app/src/controllers/shopController.ts
- app/src/repositories/ShopRepository.ts
- app/src/routes/index.ts
- app/src/routes/utils.ts
- app/src/services/ShopService.ts
> insert shop schedule

- app/src/client/controllers/signUpController.ts
- app/src/client/services/SignUpService.ts
- app/src/controllers/authController.ts
- app/src/controllers/locationController.ts
- app/src/controllers/reservationController.ts
- app/src/controllers/roleController.ts
- app/src/controllers/shopController.ts
- app/src/controllers/stylistController.ts
- app/src/controllers/userController.ts
- app/src/controllers/utils/passport.ts
- app/src/routes/api.ts
- app/src/routes/index.ts
- app/src/routes/utils.ts
- app/src/services/AuthService.ts
> I99 route reconstruct

- app/package.json
- app/prisma/migrations/20210807081422_add_menu_id_to_shop_table/migration.sql
- app/prisma/migrations/20210807082544_/migration.sql
- app/prisma/migrations/20210807163905_menu_item_from_unique_to_not/migration.sql
- app/prisma/migrations/20210809152829_make_shopid_of_menu_unique/migration.sql
- app/prisma/schema.prisma
- app/seedFiles/seed.ts
- app/seedFiles/shopSeeder.ts
- app/src/client/services/SignUpService.ts
- app/src/controllers/menuController.ts
- app/src/controllers/schemas/menu.ts
- app/src/errorHandler.ts
- app/src/repositories/ShopRepository.ts
- app/src/routes/errors.ts
- app/src/routes/index.ts
- app/src/routes/utils.ts
- app/src/services/ShopService.ts
> I82 shopmenu

- app/src/repositories/UserRepository.ts
- app/src/services/UserService.ts
> hash password

- app/src/controllers/authController.ts
- app/src/controllers/utils/passport.ts
> fix local login

- app/src/errorHandler.ts
- app/src/routes/error.ts
- app/src/routes/index.ts
- app/src/services/UserService.ts
> check duplicate user email

- app/src/controllers/authController.ts
- app/src/controllers/dashboardController.ts
- app/src/repositories/CommonRepository.ts
- app/src/repositories/LocationRepository.ts
- app/src/repositories/ReservationRepository.ts
- app/src/repositories/RoleRepository.ts
- app/src/repositories/ShopRepository.ts
- app/src/repositories/StylistRepository.ts
- app/src/repositories/UserRepository.ts
- app/src/routes/index.ts
- app/src/routes/utils.ts
- app/src/services/AuthService.ts
- app/src/services/LocationService.ts
- app/src/services/ReservationService.ts
- app/src/services/RoleService.ts
- app/src/services/ShopService.ts
- app/src/services/StylistService.ts
- app/src/services/UserService.ts
> add dashboard

- app/prisma/migrations/20210813055511_change_shop_and_stylist_from_many_to_many_relation_to_1_to_many_relation/migration.sql
- app/prisma/migrations/20210813064636_add_price_to_stylist/migration.sql
- app/prisma/schema.prisma
- app/seedFiles/seed.ts
- app/src/controllers/schemas/stylist.ts
- app/src/controllers/shopController.ts
- app/src/repositories/ReservationRepository.ts
- app/src/repositories/ShopRepository.ts
- app/src/repositories/StylistRepository.ts
- app/src/services/ShopService.ts
- app/src/services/StylistService.ts
> change stylist and shop relation

- .gitmodules
- app/src/controllers/authController.ts
- app/src/controllers/locationController.ts
- app/src/controllers/menuController.ts
- app/src/controllers/reservationController.ts
- app/src/controllers/roleController.ts
- app/src/controllers/shopController.ts
- app/src/controllers/stylistController.ts
- app/src/controllers/userController.ts
- app/src/controllers/utils/passport.ts
- app/src/services/AuthService.ts
- app/src/services/RoleService.ts
- app/src/services/ShopService.ts
- app/src/services/StylistService.ts
- app/src/services/UserService.ts
> add req and response submodule

- app/src/controllers/reservationController.ts
- app/src/controllers/schemas/reservation.ts
- app/src/controllers/shopController.ts
- app/src/repositories/ReservationRepository.ts
- app/src/services/ReservationService.ts
> I113 reservation

- docker/server/Dockerfile
> make docker use cache for copying files

- .gitignore
- app/package-lock.json
- app/package.json
- app/prisma/migrations/20210821065541_/migration.sql
- app/prisma/schema.prisma
- app/src/client/controllers/authController.ts
- app/src/client/controllers/schemas/auth.ts
- app/src/client/repositories/UserRepository.ts
- app/src/client/services/AuthService.ts
- app/src/controllers/authController.ts
- app/src/controllers/utils/passport.ts
- app/src/routes/api.ts
- app/src/routes/errors.ts
- app/src/routes/index.ts
- app/src/routes/utils.ts
- app/src/services/AuthService.ts
- app/src/services/Errors/ServiceError.ts
> I112 client login

- app/seedFiles/seed.ts
- app/src/repositories/LocationRepository.ts
- app/src/repositories/ReservationRepository.ts
- app/src/repositories/RoleRepository.ts
- app/src/repositories/ShopRepository.ts
- app/src/repositories/StylistRepository.ts
- app/src/repositories/UserRepository.ts
> code clean up

- app/src/client/controllers/authController.ts
- app/src/client/repositories/UserRepository.ts
- app/src/client/services/AuthService.ts
- app/src/controllers/authController.ts
- app/src/controllers/userController.ts
- app/src/controllers/utils/passport.ts
- app/src/middlewares/passport.ts
- app/src/repositories/ShopRepository.ts
- app/src/repositories/UserRepository.ts
- app/src/routes/utils.ts
- app/src/services/AuthService.ts
> move conversion to repository and did some code clean up

- app/src/controllers/reservationController.ts
- app/src/controllers/roleController.ts
- app/src/controllers/schemas/search.ts
- app/src/controllers/shopController.ts
- app/src/controllers/userController.ts
- app/src/repositories/ReservationRepository.ts
- app/src/repositories/RoleRepository.ts
- app/src/repositories/ShopRepository.ts
- app/src/repositories/UserRepository.ts
- app/src/services/ReservationService.ts
- app/src/services/RoleService.ts
- app/src/services/ShopService.ts
- app/src/services/UserService.ts
> added the search functonality

- app/src/controllers/locationController.ts
- app/src/repositories/LocationRepository.ts
- app/src/services/LocationService.ts
> add show endpoint for locations

- app/src/controllers/schemas/shop.ts
- app/src/controllers/shopController.ts
- app/src/repositories/ShopRepository.ts
- app/src/services/ShopService.ts
> merge shop schedule logic with shop main logic

- app/prisma/migrations/20211127080809_add_shop_user_table/migration.sql
- app/prisma/schema.prisma
- app/seedFiles/seed.ts
- app/src/controller-adapter/Dashboard.ts
- app/src/controllers/dashboardController.ts
- app/src/repositories/ReservationRepository.ts
- app/src/repositories/ShopRepository.ts
- app/src/routes/index.ts
- app/src/services/ReservationService.ts
- app/src/services/ShopService.ts
サロンのスタッフがログインした時のダッシュボードのエンドポイントの追加
> add dashboard for salon

- app/src/controllers/schemas/user.ts
- app/src/repositories/RoleRepository.ts
- app/src/repositories/UserRepository.ts
- app/src/services/UserService.ts
> id to slug

- app/prisma/migrations/20211209155917_swap_to_lowercase/migration.sql
- app/prisma/migrations/20211209160145_make_shop_staff_own_multiple_shops/migration.sql
- app/prisma/schema.prisma
- app/src/controllers/authController.ts
- app/src/controllers/shopController.ts
- app/src/services/ShopService.ts
> Role logic refactor

- app/prisma/migrations/20211212081711_add_menu_item_to_reservation/migration.sql
- app/prisma/schema.prisma
- app/seedFiles/seed.ts
- app/src/controllers/schemas/reservation.ts
- app/src/controllers/shopController.ts
- app/src/repositories/ReservationRepository.ts
- app/src/repositories/ShopRepository.ts
- app/src/services/ShopService.ts
> add menu item to reservation params

- app/prisma/migrations/20211212071056_/migration.sql
- app/prisma/schema.prisma
- app/src/controllers/schemas/stylist.ts
- app/src/controllers/shopController.ts
- app/src/repositories/ShopRepository.ts
- app/src/repositories/StylistRepository.ts
- app/src/services/ShopService.ts
> added stylist Schedule

- app/src/services/AuthService.ts
- app/src/services/ShopService.ts
- app/src/services/UserService.ts
> add error messages

- app/src/controller-adapter/Auth.ts
- app/src/controller-adapter/Dashboard.ts
- app/src/controller-adapter/Location.ts
- app/src/controller-adapter/Shop.ts
- app/src/controller-adapter/User.ts
- app/src/controllers/auth/AuthController.ts
- app/src/controllers/auth/middlewares/passport.ts
- app/src/controllers/auth/schemas.ts
- app/src/controllers/auth/schemas/google.ts
- app/src/controllers/menu/MenuController.ts
- app/src/controllers/menu/repositories/MenuRepository.ts
- app/src/controllers/menu/repositories/ShopRepository.ts
- app/src/controllers/menu/schemas.ts
- app/src/controllers/menu/services/MenuService.ts
- app/src/controllers/menu/services/ServiceError.ts
- app/src/controllers/shop/ShopController.ts
- app/src/controllers/shop/repositories/ShopRepository.ts
- app/src/controllers/shop/services/ShopService.ts
- app/src/controllers/shop/services/UserService.ts
- app/src/controllers/user/UserController.ts
- app/src/controllers/user/schemas.ts
- app/src/controllers/user/schemas/indexSchema.ts
- app/src/controllers/user/schemas/search.ts
- app/tsconfig.json
> created menu controller

- app/src/controller-adapter/Location.ts
- app/src/controller-adapter/Shop.ts
- app/src/controllers/auth/AuthController.ts
- app/src/controllers/auth/services/UserService.ts
- app/src/controllers/client/services/SignUpService.ts
- app/src/controllers/client/services/UserService.ts
- app/src/controllers/dashboard/repositories/StylistRepository.ts
- app/src/controllers/dashboard/services/ShopService.ts
- app/src/controllers/dashboard/services/StylistService.ts
- app/src/controllers/menu/MenuController.ts
- app/src/controllers/menu/repositories/MenuRepository.ts
- app/src/controllers/menu/services/MenuService.ts
- app/src/controllers/shop/ShopController.ts
- app/src/controllers/shop/schemas/menu.ts
- app/src/controllers/shop/services/ShopService.ts
- app/src/controllers/shop/services/UserService.ts
- app/src/controllers/stylist/StylistController.ts
- app/src/controllers/stylist/repositories/ShopRepository.ts
- app/src/controllers/stylist/repositories/StylistRepository.ts
- app/src/controllers/stylist/schemas.ts
- app/src/controllers/stylist/services/ServiceError.ts
- app/src/controllers/stylist/services/ShopService.ts
- app/src/controllers/stylist/services/StylistService.ts
- app/src/controllers/user/UserController.ts
- app/src/controllers/user/services/UserService.ts
- app/tsconfig.json
> 231 stylist endpoint

- app/src/controller-adapter/Shop.ts
- app/src/controllers/menu/services/MenuService.ts
- app/src/controllers/reservation/ReservationController.ts
- app/src/controllers/reservation/repositories/MenuRepository.ts
- app/src/controllers/reservation/repositories/ReservationRepository.ts
- app/src/controllers/reservation/repositories/StylistRepository.ts
- app/src/controllers/reservation/repositories/UserRepository.ts
- app/src/controllers/reservation/services/ReservationService.ts
- app/src/controllers/shop/ShopController.ts
- app/src/controllers/shop/services/ShopService.ts
- app/src/controllers/stylist/services/ShopService.ts
- app/src/controllers/stylist/services/StylistService.ts
> add create, update, and delete(cancel) endpoint

- app/src/controller-adapter/Shop.ts
- app/src/controllers/reservation/services/ReservationService.ts
- app/src/controllers/shop/ShopController.ts
- app/src/controllers/shop/repositories/MenuRepository.ts
- app/src/controllers/shop/repositories/ReservationRepository.ts
- app/src/controllers/shop/repositories/ShopRepository.ts
- app/src/controllers/shop/repositories/StylistRepository.ts
- app/src/controllers/shop/services/MenuService.ts
- app/src/controllers/shop/services/ReservationService.ts
- app/src/controllers/shop/services/ShopService.ts
- app/src/controllers/shop/services/StylistService.ts
- app/src/errorHandler.ts
> refactor shop endpoint

- app/src/controller-adapter/Shop.ts
- app/src/controllers/reservation/ReservationController.ts
- app/src/controllers/reservation/repositories/ReservationRepository.ts
- app/src/controllers/reservation/schemas.ts
- app/src/controllers/reservation/services/ReservationService.ts
> add reservation calendar

- .gitignore
- app/main.ts
- app/package-lock.json
- app/package.json
- app/seedFiles/seed.ts
- app/src/app.ts
- app/src/controller-adapter/Auth.ts
- app/src/controller-adapter/client/Auth.ts
- app/src/controllers/auth/services/AuthService.ts
- app/src/controllers/auth/services/UserService.ts
- app/src/controllers/client/auth/services/AuthService.ts
- app/src/controllers/client/auth/services/UserService.ts
- app/src/controllers/client/user/services/MailService.ts
- app/src/controllers/client/user/services/UserService.ts
- app/src/controllers/location/services/LocationService.ts
- app/src/controllers/menu/services/MenuService.ts
- app/src/controllers/reservation/services/ReservationService.ts
- app/src/controllers/shop/services/MenuService.ts
- app/src/controllers/shop/services/ReservationService.ts
- app/src/controllers/shop/services/ShopService.ts
- app/src/controllers/shop/services/StylistService.ts
- app/src/controllers/stylist/services/ShopService.ts
- app/src/controllers/stylist/services/StylistService.ts
- app/src/controllers/user/services/UserService.ts
- app/src/errorHandler.ts
- app/src/lib/Logger.ts
- app/src/lib/MorganMiddleware.ts
- app/src/routes/index.ts
- app/tsconfig.json
> Add logger

- app/package-lock.json
- app/src/controllers/dashboard/DashboardController.ts
- app/src/controllers/dashboard/repositories/MenuRepository.ts
- app/src/controllers/dashboard/services/MenuService.ts
- app/src/controllers/reservation/services/ReservationService.ts
> Popular menu

- app/src/controller-adapter/client/Shop.ts
- app/src/controllers/client/menu/MenuController.ts
- app/src/controllers/client/menu/repositories/MenuRepository.ts
- app/src/controllers/client/menu/schemas.ts
- app/src/controllers/client/menu/services/MenuService.ts
> add menu endpoint

- app/src/controller-adapter/client/Shop.ts
- app/src/controllers/client/menu/MenuController.ts
- app/src/controllers/client/stylist/StylistController.ts
- app/src/controllers/client/stylist/repositories/StylistRepository.ts
- app/src/controllers/client/stylist/schemas.ts
- app/src/controllers/client/stylist/services/StylistService.ts
> add stylists endpoint for client

- app/src/controller-adapter/client/Shop.ts
- app/src/controllers/client/reservation/ReservationController.ts
- app/src/controllers/client/reservation/repositories/MenuRepository.ts
- app/src/controllers/client/reservation/repositories/ReservationRepository.ts
- app/src/controllers/client/reservation/repositories/StylistRepository.ts
- app/src/controllers/client/reservation/schemas.ts
- app/src/controllers/client/reservation/services/ReservationService.ts
- app/src/controllers/client/reservation/services/ServiceError.ts
- app/src/controllers/client/shop/services/MenuService.ts
- app/src/controllers/client/shop/services/ShopService.ts
- app/src/controllers/reservation/repositories/ReservationRepository.ts
- app/src/controllers/stylist/repositories/StylistRepository.ts
> add reservation availability endpoint

- app/seedFiles/seed.ts
- app/src/controller-adapter/client/Shop.ts
- app/src/controllers/client/menu/schemas.ts
- app/src/controllers/client/reservation/ReservationController.ts
- app/src/controllers/client/reservation/repositories/MenuRepository.ts
- app/src/controllers/client/reservation/repositories/ReservationRepository.ts
- app/src/controllers/client/reservation/repositories/ShopRepository.ts
- app/src/controllers/client/reservation/repositories/StylistRepository.ts
- app/src/controllers/client/reservation/schemas.ts
- app/src/controllers/client/reservation/services/ReservationService.ts
- app/src/controllers/client/shop/schemas.ts
- app/src/controllers/client/stylist/schemas.ts
- app/src/controllers/dashboard/services/ShopService.ts
- app/src/controllers/dashboard/services/StylistService.ts
- app/src/controllers/dashboard/services/UserService.ts
- app/src/controllers/menu/schemas.ts
- app/src/controllers/reservation/schemas.ts
- app/src/controllers/shop/ShopController.ts
- app/src/controllers/shop/schemas.ts
- app/src/controllers/shop/services/ReservationService.ts
- app/src/controllers/shop/services/StylistService.ts
- app/src/controllers/stylist/StylistController.ts
- app/src/controllers/stylist/schemas.ts
- app/src/entities/Common.ts
- app/src/errorHandler.ts
> [wip] Add reservation create logic for client

- app/src/controllers/reservation/ReservationController.ts
- app/src/controllers/reservation/services/ReservationService.ts
- app/src/controllers/shop/ShopController.ts
- app/src/controllers/shop/schemas.ts
- app/src/controllers/stylist/StylistController.ts
- app/src/controllers/stylist/schemas.ts
> 279 convert dates

- app/src/controller-adapter/client/Shop.ts
- app/src/controllers/client/shop/ShopController.ts
- app/src/controllers/client/stylist/StylistController.ts
- app/src/controllers/stylist/StylistController.ts
> Stylist schedule

- app/src/controllers/client/reservation/services/ReservationService.ts
- app/src/controllers/reservation/services/ReservationService.ts
- app/src/controllers/shop/services/ShopService.ts
- app/src/controllers/stylist/StylistController.ts
- app/src/controllers/stylist/repositories/ShopRepository.ts
- app/src/controllers/stylist/services/StylistService.ts
- app/src/lib/ScheduleChecker.ts
> add stylist schedule check with shop schedule

- aliases.sh
- app/src/controllers/client/menu/services/MenuService.ts
- app/src/controllers/client/reservation/services/ReservationService.ts
- app/src/controllers/cron/CronController.ts
- app/src/controllers/cron/repositories/ReservationRepository.ts
- app/src/controllers/cron/services/MenuService.ts
- app/src/controllers/cron/services/ReservationService.ts
- app/src/controllers/dashboard/services/MenuService.ts
- app/src/controllers/reservation/services/ReservationService.ts
- app/src/lib/Cron.ts
- app/src/lib/Today.ts
- app/test.ts
> Add cron for reservations

- app/src/controller-adapter/User.ts
add user list access for shop staff
> shop list for shop staff

- app/src/controller-adapter/client/Shop.ts
- app/src/controllers/client/auth/repositories/UserRepository.ts
- app/src/controllers/client/shop/ShopController.ts
- app/src/controllers/client/shop/repositories/LocationRepository.ts
- app/src/controllers/client/shop/repositories/MenuRepository.ts
- app/src/controllers/client/shop/repositories/ShopRepository.ts
- app/src/controllers/client/shop/repositories/StylistRepository.ts
- app/src/controllers/client/shop/schemas.ts
- app/src/controllers/client/shop/services/ShopService.ts
- app/src/controllers/dashboard/repositories/MenuRepository.ts
- app/src/controllers/menu/repositories/ShopRepository.ts
> add shop search for clientg

- app/src/controller-adapter/Auth.ts
- app/src/controller-adapter/client/Location.ts
- app/src/controllers/auth/AuthController.ts
- app/src/controllers/auth/services/AuthService.ts
- app/src/controllers/client/location/LocationController.ts
- app/src/controllers/client/location/repositories/LocationRepository.ts
- app/src/controllers/client/location/services/LocationService.ts
- app/src/controllers/reservation/repositories/ShopRepository.ts
- app/src/controllers/reservation/services/ReservationService.ts
- app/src/routes/api.ts
- app/test.ts
> Client location endpoint

- app/src/controller-adapter/Shop.ts
- app/src/controller-adapter/Tag.ts
- app/src/controller-adapter/User.ts
- app/src/controllers/shop/ShopController.ts
- app/src/controllers/shop/repositories/ShopRepository.ts
- app/src/controllers/shop/services/ShopService.ts
- app/src/controllers/shop/services/TagService.ts
- app/src/controllers/tag/TagController.ts
- app/src/controllers/tag/repositories/TagRepository.ts
- app/src/controllers/tag/schemas.ts
- app/src/controllers/tag/services/TagService.ts
- app/src/controllers/user/UserController.ts
- app/src/controllers/user/repositories/UserRepository.ts
- app/src/controllers/user/services/UserService.ts
> Add tags search

- app/src/controller-adapter/client/Tag.ts
- app/src/controllers/client/tag/TagController.ts
- app/src/controllers/client/tag/repositories/TagRepository.ts
- app/src/controllers/client/tag/schemas.ts
- app/src/controllers/client/tag/services/TagService.ts
- app/src/routes/api.ts
> add tag search endpoint - client

- app/src/controller-adapter/client/User.ts
- app/src/controllers/client/reservation/ReservationController.ts
- app/src/controllers/client/user/UserController.ts
- app/src/controllers/client/user/repositories/UserRepository.ts
- app/src/controllers/client/user/schemas.ts
- app/src/controllers/client/user/services/UserService.ts
- app/src/controllers/user/UserController.ts
- app/src/controllers/user/services/UserService.ts
> add user detail update endpoint

- app/src/controller-adapter/client/User.ts
- app/src/controllers/client/reservation/ReservationController.ts
- app/src/controllers/client/reservation/repositories/MenuRepository.ts
- app/src/controllers/client/reservation/repositories/ReservationRepository.ts
- app/src/controllers/client/reservation/repositories/ShopRepository.ts
- app/src/controllers/client/reservation/repositories/StylistRepository.ts
- app/src/controllers/client/reservation/schemas.ts
- app/src/controllers/client/reservation/services/ReservationService.ts
> add user reservations list

- app/src/controller-adapter/Shop.ts
- app/src/controllers/review/ReviewController.ts
- app/src/controllers/review/repositories/ReviewRepository.ts
- app/src/controllers/review/repositories/UserRepository.ts
- app/src/controllers/review/services/ReviewService.ts
> add review detail - admin

- app/src/controllers/cron/CronController.ts
- app/src/controllers/cron/repositories/TagRepository.ts
- app/src/controllers/cron/services/TagService.ts
- app/src/lib/Cron.ts
> clean up tags everyday at 12mn

- app/src/controller-adapter/client/User.ts
- app/src/controllers/client/reservation/ReservationController.ts
- app/src/controllers/client/reservation/repositories/ReservationRepository.ts
- app/src/controllers/client/reservation/services/ReservationService.ts
> add reservation detail endpoint - client

- app/src/controller-adapter/client/User.ts
- app/src/controllers/client/reservation/ReservationController.ts
- app/src/controllers/client/reservation/repositories/ReservationRepository.ts
- app/src/controllers/client/reservation/services/ReservationService.ts
- app/src/errors/ControllerErrors.ts
- app/src/errors/RouteErrors.ts
- app/src/errors/ServiceErrors.ts
> add user reservation cancel endpoint - client

- app/src/controller-adapter/Shop.ts
- app/src/controllers/tag/TagController.ts
- app/src/controllers/tag/repositories/ShopRepository.ts
- app/src/controllers/tag/repositories/TagRepository.ts
- app/src/controllers/tag/services/TagService.ts
> add shop tag list

- app/src/controller-adapter/client/Shop.ts
- app/src/controllers/client/shop/ShopController.ts
- app/src/controllers/client/shop/repositories/ShopRepository.ts
- app/src/controllers/client/shop/services/ShopService.ts
- app/src/controllers/cron/CronController.ts
- app/src/controllers/cron/repositories/ShopRepository.ts
- app/src/controllers/cron/services/ShopService.ts
- app/src/lib/Cron.ts
- app/src/lib/PopularShopSetter.ts
> Shop ranking
